[package]
name = "tuvero"
version = "0.1.1"
edition = "2021"

description = "Tournament management library, with a variety of tournament systems"
license = "MIT"
repository = "https://github.com/elor/tuvero.rs"

include = ["src/**/*", "Cargo.toml"]

[dependencies]
